version: '2.1'

services:

  app:
    image: ${IMAGE}:${IMAGE_VER}
    restart: always
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${APP_SITE}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../../data/gotify:/app/data
    environment:
      - GOTIFY_SERVER_PORT=80
      - GOTIFY_SERVER_SSL_ENABLED=false
      - GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=false
#      - GOTIFY_SERVER_LISTENADDR=0.0.0.0
      - GOTIFY_DATABASE_DIALECT=postgres
      - GOTIFY_DATABASE_CONNECTION=host=${PGHOST} port=5432 user=${PGUSER} dbname=${PGDATABASE} password=${PGPASSWORD} sslmode=${PGSSLMODE}
      - GOTIFY_DEFAULTUSER_NAME=${ADMIN_USER}
      - GOTIFY_DEFAULTUSER_PASS=${ADMIN_PASS}

networks:
  lan:
    external:
      name: ${DCAPE_NET}

